<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Гостевая книга');

echo $this->doctype();
?>

<html>
<head>
    <?php
    echo $this->headMeta();
    ?>
    <?php
    echo $this->headTitle();
    ?>
    <?=$this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');?>
</head>
<body>
<div id="content">
    <h1><?=$this->escape($this->title);?></h1>
    <?=$this->layout()->content;?>
</div>
</body>
</html>
